SET SQL_SAFE_UPDATES = 0;
UPDATE avs_be.sys_parameters SET param_value= 'https://{{ AVS_PUBLIC_FQDN }}/#!/register/stepTwo?' WHERE param_name = 'CONFIRMATION_URL';
UPDATE avs_be.sys_parameters SET param_value= 'http://{{ AVS_PUBLIC_FQDN }}/AVS/besc?action=ChangePassword&' WHERE param_name = 'RESET_URL';
UPDATE avs_be.sys_parameters SET param_value= '{{ WIKIPEDIA_URL }}' WHERE param_name = 'WIKIPEDIA_URL';
UPDATE avs_be.sys_parameters SET param_value= '{{ AMAZON_URL }}' WHERE param_name = 'AMAZON_URL';
UPDATE avs_be.sys_parameters SET param_value= '{{ TWITTER_URL }}' WHERE param_name = 'TWITTER_URL';
UPDATE avs_be.sys_parameters SET param_value= '{{ EXTERNAL_SSO_SYSTEM_URL }}' WHERE param_name = 'EXTERNAL_SSO_SYSTEM_URL';
UPDATE avs_be.sys_parameters SET param_value= '{{ EXTERNAL_SSO_SERVICE_URL }}' WHERE param_name = 'EXTERNAL_SSO_SERVICE_URL';
UPDATE avs_be.sys_parameters SET param_value= 'http://{{ WV_LICENSE_SERVER_URL }}/widevine' WHERE param_name = 'WV_LICENSE_SERVER_URL';
UPDATE avs_be.sys_parameters SET param_value= '{{ WSDL_PAYPAL_SOAP }}' WHERE param_name = 'WSDL_PAYPAL_SOAP';
UPDATE avs_be.sys_parameters SET param_value= 'http://{{ IDENTITY_SERVICE_PORTAL_WSDL_URL }}/IdentityServicePortalStub?wsdl' WHERE param_name = 'IDENTITY_SERVICE_PORTAL_WSDL_URL';
UPDATE avs_be.sys_parameters SET param_value= 'https://{{ SAML_TOKEN_AUDIENCE_URI }}/' WHERE param_name = 'SAML_TOKEN_AUDIENCE_URI';
UPDATE avs_be.sys_parameters SET param_value= '{{ SAML_TOKEN_DEVICE_ID_ATTRIBUTE }}' WHERE param_name = 'SAML_TOKEN_DEVICE_ID_ATTRIBUTE';
UPDATE avs_be.sys_parameters SET param_value= '{{ SAML_TOKEN_LIVE_TYPE_ATTRIBURTE }}' WHERE param_name = 'SAML_TOKEN_LIVE_TYPE_ATTRIBURTE';
UPDATE avs_be.sys_parameters SET param_value= 'http://{{ BASE_URL_NPVR_EXTERNAL_SYSTEM }}/AVSNPVR/besc?' WHERE param_name = 'BASE_URL_NPVR_EXTERNAL_SYSTEM';
UPDATE avs_be.sys_parameters SET param_value= 'http://{{ URL_REFLECTOR }}/RL/GetResourceLocator.php?' WHERE param_name = 'URL_REFLECTOR';
SET SQL_SAFE_UPDATES = 1;