SET SQL_SAFE_UPDATES = 0;
UPDATE rpgw.sys_parameters SET param_value= 'https://{{ AVS_PUBLIC_FQDN }}/paypalTransaction?paymMethod=PAYPAL&action=confirm' WHERE param_name = 'PP_RETURN_URL';
UPDATE rpgw.sys_parameters SET param_value= 'https://{{ AVS_PUBLIC_FQDN }}/paypalTransaction?paymMethod=PAYPAL&action=cancel' WHERE param_name = 'PP_CANCEL_URL';
UPDATE rpgw.sys_parameters SET param_value= '{{ PP_FORWARD_URL }}' WHERE param_name = 'PP_FORWARD_URL';
UPDATE rpgw.sys_parameters SET param_value= '{{ PP_SANDBOX_API_URL }}' WHERE param_name = 'PP_SANDBOX_API_URL';
UPDATE rpgw.sys_parameters SET param_value= '{{ PP_LIVE_API_URL }}' WHERE param_name = 'PP_LIVE_API_URL';
UPDATE rpgw.sys_parameters SET param_value= '{{ DOXEE_CONNECTION_URL }}' WHERE param_name = 'DOXEE_CONNECTION_URL';
UPDATE rpgw.sys_parameters SET param_value= '{{ VF_ENDPOINT }}' WHERE param_name = 'VF_ENDPOINT';
UPDATE rpgw.sys_parameters SET param_value= 'http://{{ APPLE_VERIFY_RECEIPT_URL }}/verifyReceipt' WHERE param_name = 'APPLE_VERIFY_RECEIPT_URL';
SET SQL_SAFE_UPDATES = 1;